### ISSUE TITLE
Branch name regex support

### ISSUE THREAD

**Issue by bh86** [kevinoid/git-branch-is#22]
Hi,

Is it possible to support Regex as the branch name? it will be very helpful to target multiple branches or a naming convention (e.g. feature branch).

Thanks.

**Comment by Norbz** [comment]
I agree, I ran into the same issue while using git flow. Ability to match branches like release/vx.y.z would be great.

I would recommand using minimatch, using the glob syntax, over regexp as it is way more easy to write and should be enough for all cases.

I forked the repo and wil try to do it myself if I find some time to do it.

**Comment by kevinoid** [comment]
Thanks for the suggestion @bh86.  I've added support in b1834f0 (and support for case-insensitive matching in bc4485f).  Do those look like they will work for you?  If so, I'm planning to make a release after making a decision on #23.
