### ISSUE TITLE
git-branch-is-not

### ISSUE THREAD

**Issue by sarneeh** [kevinoid/git-branch-is#28]
Is there any possibility to do a negation with `git-branch-is`? I'd like to do something like `git-branch-is-not --regex "test|production"`.

**Comment by kevinoid** [comment]
That's a great idea.  Thanks for suggesting it.

How about `git-branch-is --not --regex "test|production"`?  I have implemented it in #29.  Will that fit your needs?

**Comment by sarneeh** [comment]
@kevinoid Absolutely! Wow, that was fast! 😄

**Comment by kevinoid** [comment]
@sarneeh Great, glad to hear it!  Thanks for reviewing the changes.

I just published version 2.1.0 which includes #29.  Let me know if that doesn't solve the issue for you.

**Comment by sarneeh** [comment]
Awesome :) Thank you very much for a fast implementation and publish! 🎉
